DECLARE 
    NUM1 NUMBER;
    NUM2 NUMBER;
    SOMA NUMBER;
BEGIN
    num1 := 20;
    num2 := 2;
    SOMA := num1 / num2;
    
    DBMS_OUTPUT.PUT_LINE('SOMA É ' || SOMA);
    
EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20001, 'ERRO AO CALCULAR');
END;