

BEGIN
    DBMS_OUTPUT.PUT_LINE('OLA MUNDO!');
END;

DECLARE
    v_NUMMERO NUMBER := 50;
    v_NOME VARCHAR2(100);
BEGIN
      v_NOME := 'JANILSON';
      DBMS_OUTPUT.PUT_LINE('VALOR DA VARIÁVEL v_NUMERO É ' || v_NUMMERO);    
      DBMS_OUTPUT.PUT_LINE('VALOR DA VARIÁVEL v_NOME É ' || v_NOME);    
END;

DECLARE
    v_NUMMERO NUMBER := 50;
    v_NOME VARCHAR2(100);
BEGIN
      v_NOME := 'JANILSON';
      DBMS_OUTPUT.PUT_LINE('VALOR DA VARIÁVEL v_NUMERO É ' || v_NUMMERO);    
      DBMS_OUTPUT.PUT_LINE('VALOR DA VARIÁVEL v_NOME É ' || v_NOME);    
EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20001, 'ERRO NO PROGRAMA');    
END;

DECLARE
    v_NUMERO NUMBER;
BEGIN
    DBMS_OUTPUT.PUT_LINE('INICIO BLOCO MAIS EXTERNO!');
    
    v_NUMERO := 10;

    DBMS_OUTPUT.PUT_LINE('VALOR DE v_NUMERO É ' || v_NUMERO);
    
    DECLARE 
        v_NUMERO2 NUMBER := 2;    
    BEGIN
        DBMS_OUTPUT.PUT_LINE('INICIO BLOCO MAIS INTERNO!');
        DBMS_OUTPUT.PUT_LINE(v_NUMERO || ' DIVIDIDO POR ' || v_NUMERO2 || ' É '  || v_NUMERO / v_NUMERO2);
        DBMS_OUTPUT.PUT_LINE('FINAL BLOCO MAIS INTERNO!');
    EXCEPTION 
    --SESSÃO DE TRATAMENTO D ERROS    
    WHEN ZERO_DIVIDE THEN
        RAISE_APPLICATION_ERROR(-20001, 'IMPOSSÌVEL DIVIDIR POR ZERO!'); 
    END;
    
    DBMS_OUTPUT.PUT_LINE('FINAL BLOCO MAIS EXTERNO!');
    
EXCEPTION 
    --SESSÃO DE TRATAMENTO D ERROS   
    WHEN ZERO_DIVIDE THEN
        RAISE_APPLICATION_ERROR(-20001, 'IMPOSSÌVEL DIVIDIR POR ZERO!');  
     WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20001, 'ERRO DO PROGRAMA');  
END; 