--####################CREATE TABLE AS

SELECT * FROM TITULO_RECEBER;

DESC TITULO_RECEBER;

CREATE TABLE TITULO_PAGAR AS (SELECT NR_TITULO, CD_PESSOA_FISICA, CD_CNPJ, VL_SALDO, VL_TITULO, DT_VENCIMENTO FROM TITULO_RECEBER );

DROP TABLE TITULO_PAGAR;

SELECT * FROM TITULO_PAGAR;